debug-log: false

contexts:
  - name: "survival_in_world_nether"
    worlds:
      - "world_nether"
    gamemodes:
      - "SURVIVAL"
    inventory: "nether_survival_inventory"

  - name: "creative_in_world_end"
    worlds:
      - "world_the_end"
    gamemodes:
      - "CREATIVE"
    inventory: "end_creative_inventory"

default_contexts: "default_inventory"

database:
  type: "sqlite"  # "sqlite" ou "mysql"

  sqlite:
    file: "database.db"

  mysql:
    host: "localhost"
    port: 3306
    database: "inventory_manager"
    username: "root"
    password: "password"
